name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
      
      - name: Install Dependencies and Run Tests
        run: |
          cd frontend && 
          npm install &&
          npm start
          npm build
          echo "all backend dependencies have been installed"
          cd ..
          cd backend &&
          npm install &&
          npm start
          echo "all backend dependencies have been installed"