name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install npm dependencies
        run: |
          npm install
          npm run install:frontend
          npm run install:backend

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:frontend, npm run start:server
          wait-on: 'http://localhost:3000'
          command: npm test
          